# Generated by Django 5.0.6 on 2026-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='goal_type',
            field=models.CharField(choices=[('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain'), ('high_calorie', 'High Calorie')], default='weight_gain', max_length=15),
        ),
    ]
