# Generated by Django 5.0.6 on 2026-07-09 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('water_liters', models.FloatField(blank=True, null=True)),
                ('workout_done', models.BooleanField(default=False)),
                ('meditation_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('walking_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_consumed', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_consumed', models.FloatField(blank=True, null=True)),
                ('mood', models.PositiveIntegerField(blank=True, help_text='1-10', null=True)),
                ('energy_level', models.PositiveIntegerField(blank=True, help_text='1-10', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
